### PR TITLE
Docker Name Support

### PR DESCRIPTION
**Pull request by esterlinej**
Changes
---
MAKEFILE
- update docker-build
- add docker-furan-builder
- add .PHONY

GO MOD
- update go.sum

CMD TRIGGER
- add flag for dockerfile-name

BUILDER
- update bkrunner.sh Dockerfile to match current image version

PROTOS
- add dockerfile_name to api build definition

PKG GENERATED FURANRPC
- updates per proto change

PKG GRPC / BUILDKIT / MODELS
- add dockerfile name support for build options
- add / update tests for dockerfile name

PKG JOBRUNNER
- update BuildKitImage

### CODE REVIEW

**Review by michaelNorris01 — APPROVED** [review]
LGTM!

**Comment by esterlinej** [comment]
Confirmed working from hello-kube test branch with multiple Dockerfile names.
```
➜  hello-kube git:(je-test-dockername) furan trigger --github-repo Pluto-tv/hello-kube --tags dqa-je-test-dockername-2 --image-repos 479133078108.dkr.ecr.us-east-1.amazonaws.com/furan --build-cache-type s3 --api-key $FDQA_API_KEY --tls-skip-verify --source-ref je-test-dockername --remote-host 127.0.0.1:4000 --dockerfile-name Dockerfile-foo
build started: 9a14005f-8998-49a2-a7af-ddfce797ffc8
creating build job (status: NOTSTARTED)
job created: furan-build-pluto-tv-hello-kube-9a14005f-8998-49a2-a7af-ddfce7 (status: NOTSTARTED)
job running, handoff successful
build is running (handoff took 5.928414767s)
downloading cache: s3://devops-acyl/furan/dqa/use1/1/Pluto-tv/hello-kube_buildcache.tar.gz
successfully downloaded cache from S3 (size 45670409 bytes; elapsed: 556.055446ms)
successfully unarchived build cache (elapsed: 18.58762ms)
#1 [internal] load build definition from Dockerfile-foo
#1 transferring dockerfile: 1.19kB done
#1 DONE 0.0s
#2 [internal] load .dockerignore
#2 transferring context: 88B done
#2 DONE 0.1s
#3 [internal] load metadata for docker.io/library/node:16-alpine3.13
#3 DONE 0.3s
#4 [internal] load build context
#4 transferring context: 85.34kB done
#4 DONE 0.1s
#5 [1/6] FROM docker.io/library/node:16-alpine3.13@sha256:c7f8af31c7c4bb2221da18b67ccbe6d0632dab86d015573857b5a91afbedcf8c
#5 resolve docker.io/library/node:16-alpine3.13@sha256:c7f8af31c7c4bb2221da18b67ccbe6d0632dab86d015573857b5a91afbedcf8c 0.0s done
#5 sha256:be83d68ed338fbfb286cc99e41f65af1efee201aff73e6f0288e034075f69d52 452B / 452B 0.1s done
#5 sha256:5758d4e389a3f662e94a85fb76143dbe338b64f8d2a65f45536a9663b05305ad 2.82MB / 2.82MB 0.1s done
#5 extracting sha256:5758d4e389a3f662e94a85fb76143dbe338b64f8d2a65f45536a9663b05305ad
#5 sha256:fe728f6388df9c8f5eae907e8198b8d65bdc2ace9460298f2c9162c2974df29b 0B / 2.35MB 0.2s
#5 extracting sha256:5758d4e389a3f662e94a85fb76143dbe338b64f8d2a65f45536a9663b05305ad 0.1s done
#5 sha256:fe728f6388df9c8f5eae907e8198b8d65bdc2ace9460298f2c9162c2974df29b 2.35MB / 2.35MB 0.3s done
#5 sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9 0B / 34.81MB 0.2s
#5 sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9 13.63MB / 34.81MB 0.3s
#5 sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9 17.83MB / 34.81MB 0.5s
#5 sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9 34.81MB / 34.81MB 0.7s done
#5 extracting sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9
#5 extracting sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9 1.5s done
#5 DONE 2.4s
#5 [1/6] FROM docker.io/library/node:16-alpine3.13@sha256:c7f8af31c7c4bb2221da18b67ccbe6d0632dab86d015573857b5a91afbedcf8c
#5 extracting sha256:fe728f6388df9c8f5eae907e8198b8d65bdc2ace9460298f2c9162c2974df29b
#5 extracting sha256:fe728f6388df9c8f5eae907e8198b8d65bdc2ace9460298f2c9162c2974df29b 0.3s done
#5 DONE 2.7s
#5 [1/6] FROM docker.io/library/node:16-alpine3.13@sha256:c7f8af31c7c4bb2221da18b67ccbe6d0632dab86d015573857b5a91afbedcf8c
#5 extracting sha256:be83d68ed338fbfb286cc99e41f65af1efee201aff73e6f0288e034075f69d52
#5 extracting sha256:be83d68ed338fbfb286cc99e41f65af1efee201aff73e6f0288e034075f69d52 0.2s done
#5 DONE 2.9s
#6 [2/6] RUN mkdir -p /usr/src/app
#6 DONE 0.3s
#7 [3/6] WORKDIR /usr/src/app
#7 DONE 0.2s
#8 [4/6] COPY src/app/package.json /usr/src/app/
#8 DONE 0.3s
#9 [5/6] RUN npm install
#9 4.297 npm WARN deprecated express-pino-logger@6.0.0: use pino-http instead
#9 4.560
#9 4.560 added 90 packages, and audited 91 packages in 3s
#9 4.560
#9 4.560 10 packages are looking for funding
#9 4.560   run `npm fund` for details
#9 4.561
#9 4.561 found 0 vulnerabilities
#9 4.562 npm notice
#9 4.562 npm notice New major version of npm available! 8.1.2 -> 10.2.0
#9 4.562 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.0>
#9 4.562 npm notice Run `npm install -g npm@10.2.0` to update!
#9 4.562 npm notice
#9 DONE 4.6s
#10 [6/6] COPY src/app /usr/src/app
#10 DONE 0.4s
#11 exporting to image
#11 exporting layers
#11 exporting layers 2.4s done
#11 exporting manifest sha256:c3e4d9b212ee74702e3adc3b6fdbe7556310aaa087349fcde1b9d757cdce5734 done
#11 exporting config sha256:f3dac2804d29998badc5653a98df145528645972e8c6bfcbe3d3406bb2a2397b done
#11 pushing layers
#11 pushing layers 1.0s done
#11 pushing manifest for 479133078108.dkr.ecr.us-east-1.amazonaws.com/furan:dqa-je-test-dockername-2@sha256:c3e4d9b212ee74702e3adc3b6fdbe7556310aaa087349fcde1b9d757cdce5734
#11 pushing manifest for 479133078108.dkr.ecr.us-east-1.amazonaws.com/furan:dqa-je-test-dockername-2@sha256:c3e4d9b212ee74702e3adc3b6fdbe7556310aaa087349fcde1b9d757cdce5734 0.3s done
#11 pushing layers 0.1s done
#11 pushing manifest for 479133078108.dkr.ecr.us-east-1.amazonaws.com/furan:08b80ad1db62d9a0500869394791bc93a0da7c39@sha256:c3e4d9b212ee74702e3adc3b6fdbe7556310aaa087349fcde1b9d757cdce5734
#11 pushing manifest for 479133078108.dkr.ecr.us-east-1.amazonaws.com/furan:08b80ad1db62d9a0500869394791bc93a0da7c39@sha256:c3e4d9b212ee74702e3adc3b6fdbe7556310aaa087349fcde1b9d757cdce5734 0.2s done
#11 DONE 4.0s
#12 exporting content cache
#12 preparing build cache for export
#12 writing layer sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
#12 writing layer sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 done
#12 writing layer sha256:52637696b5adfa871953c56bdc2fbd57397f80710ed18e5ca3269cc65407427b done
#12 writing layer sha256:5758d4e389a3f662e94a85fb76143dbe338b64f8d2a65f45536a9663b05305ad 0.0s done
#12 writing layer sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9
#12 writing layer sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9 0.5s done
#12 writing layer sha256:6679e428570ab51b1ccdc744e017efb790482de25037516119125b6dd0a9434e 0.1s done
#12 writing layer sha256:9b195a1093af4d66d258604effe9d1ff62e5f2b9119284868428f200776d609f 0.0s done
#12 writing layer sha256:afea2ecce60788d82a8bdc4cf1582928c9df48bc408b3f80fc9b120bf352bc06
#12 preparing build cache for export 0.7s done
#12 writing layer sha256:afea2ecce60788d82a8bdc4cf1582928c9df48bc408b3f80fc9b120bf352bc06 done
#12 writing layer sha256:be83d68ed338fbfb286cc99e41f65af1efee201aff73e6f0288e034075f69d52 done
#12 writing layer sha256:fe728f6388df9c8f5eae907e8198b8d65bdc2ace9460298f2c9162c2974df29b 0.0s done
#12 writing config sha256:5ad3a0a1a379f5eefc4d9e21a1117df61a22cc3293da1d48ebeaa326fc4fa11f 0.0s done
#12 writing manifest sha256:5393f4bd8f1e63fd9d762a89030287247a20d7053923de27c39c4d0141843b96 done
#12 DONE 0.7s
archiving build cache snapshot
archived build cache (elapsed: 53.862771ms)
uploading cache: s3://devops-acyl/furan/dqa/use1/1/Pluto-tv/hello-kube_buildcache.tar.gz
successfully uploaded cache from S3 (size 45684547 bytes; elapsed: 693.290577ms)
solve success: map[cache.manifest:{"mediaType":"application/vnd.oci.image.index.v1+json","digest":"sha256:5393f4bd8f1e63fd9d762a89030287247a20d7053923de27c39c4d0141843b96","size":3199} containerimage.buildinfo:eyJmcm9udGVuZCI6ImRvY2tlcmZpbGUudjAiLCJhdHRycyI6eyJmaWxlbmFtZSI6IkRvY2tlcmZpbGUtZm9vIn0sInNvdXJjZXMiOlt7InR5cGUiOiJkb2NrZXItaW1hZ2UiLCJyZWYiOiJkb2NrZXIuaW8vbGlicmFyeS9ub2RlOjE2LWFscGluZTMuMTMiLCJwaW4iOiJzaGEyNTY6YzdmOGFmMzFjN2M0YmIyMjIxZGExOGI2N2NjYmU2ZDA2MzJkYWI4NmQwMTU1NzM4NTdiNWE5MWFmYmVkY2Y4YyJ9XX0= containerimage.config.digest:sha256:f3dac2804d29998badc5653a98df145528645972e8c6bfcbe3d3406bb2a2397b containerimage.descriptor:eyJtZWRpYVR5cGUiOiJhcHBsaWNhdGlvbi92bmQuZG9ja2VyLmRpc3RyaWJ1dGlvbi5tYW5pZmVzdC52Mitqc29uIiwiZGlnZXN0Ijoic2hhMjU2OmMzZTRkOWIyMTJlZTc0NzAyZTNhZGMzYjZmZGJlNzU1NjMxMGFhYTA4NzM0OWZjZGUxYjlkNzU3Y2RjZTU3MzQiLCJzaXplIjoyMDY5LCJwbGF0Zm9ybSI6eyJhcmNoaXRlY3R1cmUiOiJhbWQ2NCIsIm9zIjoibGludXgifX0= containerimage.digest:sha256:c3e4d9b212ee74702e3adc3b6fdbe7556310aaa087349fcde1b9d757cdce5734 image.name:479133078108.dkr.ecr.us-east-1.amazonaws.com/furan:dqa-je-test-dockername-2,479133078108.dkr.ecr.us-east-1.amazonaws.com/furan:08b80ad1db62d9a0500869394791bc93a0da7c39]
build completed: state: SUCCESS (duration: 21.774863s) (100 msgs received)
```

**Review by michaelNorris01 — COMMENTED** [review]
LGTM!

**Comment by esterlinej** [comment]
Test Dockerfile Name & Path
```
➜  ~ furan trigger --github-repo Pluto-tv/hello-kube --tags dqa-je-test-dockername-3 --image-repos 972525491246.dkr.ecr.us-east-1.amazonaws.com/hello-kube --build-cache-type s3 --api-key $FDQA_API_KEY --tls-skip-verify --source-ref je-test-dockername --remote-host furan.nonprd.pluto.tv:4000 --dockerfile-name Dockerfile-dqa --dockerfile-path dqa
build started: 73348c3f-fdb7-4d0d-8c70-814921a9546d
creating build job (status: NOTSTARTED)
job created: furan-build-pluto-tv-hello-kube-73348c3f-fdb7-4d0d-8c70-814921 (status: NOTSTARTED)
job running, handoff successful
build is running (handoff took 6.309156885s)
downloading cache: s3://devops-acyl/furan/dev/use1/1/Pluto-tv/hello-kube_buildcache.tar.gz
successfully downloaded cache from S3 (size 45680260 bytes; elapsed: 796.111225ms)
successfully unarchived build cache (elapsed: 40.832663ms)
#1 [internal] load build definition from Dockerfile-dqa
#1 transferring dockerfile: 1.22kB done
#1 DONE 0.0s
#2 [internal] load .dockerignore
#2 transferring context: 88B done
#2 DONE 0.1s
#3 [internal] load metadata for docker.io/library/node:16-alpine3.13
#3 DONE 0.3s
#4 [internal] load build context
#4 transferring context: 85.34kB done
#4 DONE 0.1s
#5 [1/6] FROM docker.io/library/node:16-alpine3.13@sha256:c7f8af31c7c4bb2221da18b67ccbe6d0632dab86d015573857b5a91afbedcf8c
#5 resolve docker.io/library/node:16-alpine3.13@sha256:c7f8af31c7c4bb2221da18b67ccbe6d0632dab86d015573857b5a91afbedcf8c 0.0s done
#5 sha256:be83d68ed338fbfb286cc99e41f65af1efee201aff73e6f0288e034075f69d52 452B / 452B 0.1s done
#5 sha256:fe728f6388df9c8f5eae907e8198b8d65bdc2ace9460298f2c9162c2974df29b 0B / 2.35MB 0.2s
#5 sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9 0B / 34.81MB 0.2s
#5 sha256:5758d4e389a3f662e94a85fb76143dbe338b64f8d2a65f45536a9663b05305ad 2.82MB / 2.82MB 0.1s done
#5 extracting sha256:5758d4e389a3f662e94a85fb76143dbe338b64f8d2a65f45536a9663b05305ad
#5 sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9 7.34MB / 34.81MB 0.3s
#5 sha256:fe728f6388df9c8f5eae907e8198b8d65bdc2ace9460298f2c9162c2974df29b 2.35MB / 2.35MB 0.4s done
#5 sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9 17.83MB / 34.81MB 0.5s
#5 extracting sha256:5758d4e389a3f662e94a85fb76143dbe338b64f8d2a65f45536a9663b05305ad 0.3s done
#5 sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9 32.51MB / 34.81MB 0.8s
#5 sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9 34.81MB / 34.81MB 1.0s done
#5 extracting sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9
#5 extracting sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9 2.8s done
#5 extracting sha256:fe728f6388df9c8f5eae907e8198b8d65bdc2ace9460298f2c9162c2974df29b
#5 extracting sha256:fe728f6388df9c8f5eae907e8198b8d65bdc2ace9460298f2c9162c2974df29b 0.6s done
#5 extracting sha256:be83d68ed338fbfb286cc99e41f65af1efee201aff73e6f0288e034075f69d52
#5 extracting sha256:be83d68ed338fbfb286cc99e41f65af1efee201aff73e6f0288e034075f69d52 0.5s done
#5 DONE 5.0s
#6 [2/6] RUN mkdir -p /usr/src/app
#6 DONE 0.5s
#7 [3/6] WORKDIR /usr/src/app
#7 DONE 0.5s
#8 [4/6] COPY src/app/package.json /usr/src/app/
#8 DONE 0.5s
#9 [5/6] RUN npm install
#9 6.130 npm WARN deprecated express-pino-logger@6.0.0: use pino-http instead
#9 6.651
#9 6.651 added 90 packages, and audited 91 packages in 6s
#9 6.651
#9 6.651 10 packages are looking for funding
#9 6.651   run `npm fund` for details
#9 6.653
#9 6.653 found 0 vulnerabilities
#9 6.654 npm notice
#9 6.654 npm notice New major version of npm available! 8.1.2 -> 10.2.0
#9 6.654 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.0>
#9 6.654 npm notice Run `npm install -g npm@10.2.0` to update!
#9 6.654 npm notice
#9 DONE 6.7s
#10 [6/6] COPY src/app /usr/src/app
#10 DONE 0.7s
#11 exporting to image
#11 exporting layers
#11 exporting layers 4.3s done
#11 exporting manifest sha256:58193d9f5c0152258834cddc3b7dd43ab187bd3d4fd43c0cbf6b1823d4e84caa done
#11 exporting config sha256:00f968bfec085aeb5aaef73f0735a9ce3a72e939efaad7bd03c4f9e059b017fc done
#11 pushing layers
#11 pushing layers 0.9s done
#11 pushing manifest for 972525491246.dkr.ecr.us-east-1.amazonaws.com/hello-kube:dqa-je-test-dockername-3@sha256:58193d9f5c0152258834cddc3b7dd43ab187bd3d4fd43c0cbf6b1823d4e84caa
#11 pushing manifest for 972525491246.dkr.ecr.us-east-1.amazonaws.com/hello-kube:dqa-je-test-dockername-3@sha256:58193d9f5c0152258834cddc3b7dd43ab187bd3d4fd43c0cbf6b1823d4e84caa 0.2s done
#11 pushing layers 0.1s done
#11 pushing manifest for 972525491246.dkr.ecr.us-east-1.amazonaws.com/hello-kube:506c9805422e38ca3fa38e80bf431865192fc39b@sha256:58193d9f5c0152258834cddc3b7dd43ab187bd3d4fd43c0cbf6b1823d4e84caa
#11 pushing manifest for 972525491246.dkr.ecr.us-east-1.amazonaws.com/hello-kube:506c9805422e38ca3fa38e80bf431865192fc39b@sha256:58193d9f5c0152258834cddc3b7dd43ab187bd3d4fd43c0cbf6b1823d4e84caa 0.2s done
#11 DONE 5.8s
#12 exporting content cache
#12 preparing build cache for export
#12 writing layer sha256:0269e3ab3daa502709808e45ea3463faed416d7f0f48dd49fe305610a855681b 0.0s done
#12 writing layer sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 done
#12 writing layer sha256:5758d4e389a3f662e94a85fb76143dbe338b64f8d2a65f45536a9663b05305ad 0.0s done
#12 writing layer sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9
#12 writing layer sha256:65e45f2a771d43d1c02abac479e46650243bce5f34aefe0f6916bba4ef9fb5e9 0.8s done
#12 writing layer sha256:8287fa65f40387cb97bf88b91552eb5661958fc25db9bb703107727dc02a9fa2
#12 preparing build cache for export 1.1s done
#12 writing layer sha256:8287fa65f40387cb97bf88b91552eb5661958fc25db9bb703107727dc02a9fa2 0.1s done
#12 writing layer sha256:ae9d8c122812d54d7f4bf779e4364bb77778673de65af8a4bb6fb67fc7303747 done
#12 writing layer sha256:be83d68ed338fbfb286cc99e41f65af1efee201aff73e6f0288e034075f69d52 done
archiving build cache snapshot
#12 writing layer sha256:dc003f7943305d06e1cd6792d7f0591ea44cae4ff50e0afa2aa668f6e61dab53 done
#12 writing layer sha256:fe728f6388df9c8f5eae907e8198b8d65bdc2ace9460298f2c9162c2974df29b 0.0s done
#12 writing config sha256:65edf3677096ee802a1fc2258ea363ac2b19608363f3486f6e3aa656775141a4 done
#12 writing manifest sha256:f168fe5b6169ea0984344d5d1d1b41fa2045674afc6ba5e067e0e55d5f231f99 done
#12 DONE 1.1s
archived build cache (elapsed: 117.864449ms)
uploading cache: s3://devops-acyl/furan/dev/use1/1/Pluto-tv/hello-kube_buildcache.tar.gz
successfully uploaded cache from S3 (size 45691100 bytes; elapsed: 861.968442ms)
solve success: map[cache.manifest:{"mediaType":"application/vnd.oci.image.index.v1+json","digest":"sha256:f168fe5b6169ea0984344d5d1d1b41fa2045674afc6ba5e067e0e55d5f231f99","size":3199} containerimage.buildinfo:eyJmcm9udGVuZCI6ImRvY2tlcmZpbGUudjAiLCJhdHRycyI6eyJmaWxlbmFtZSI6IkRvY2tlcmZpbGUtZHFhIn0sInNvdXJjZXMiOlt7InR5cGUiOiJkb2NrZXItaW1hZ2UiLCJyZWYiOiJkb2NrZXIuaW8vbGlicmFyeS9ub2RlOjE2LWFscGluZTMuMTMiLCJwaW4iOiJzaGEyNTY6YzdmOGFmMzFjN2M0YmIyMjIxZGExOGI2N2NjYmU2ZDA2MzJkYWI4NmQwMTU1NzM4NTdiNWE5MWFmYmVkY2Y4YyJ9XX0= containerimage.config.digest:sha256:00f968bfec085aeb5aaef73f0735a9ce3a72e939efaad7bd03c4f9e059b017fc containerimage.descriptor:eyJtZWRpYVR5cGUiOiJhcHBsaWNhdGlvbi92bmQuZG9ja2VyLmRpc3RyaWJ1dGlvbi5tYW5pZmVzdC52Mitqc29uIiwiZGlnZXN0Ijoic2hhMjU2OjU4MTkzZDlmNWMwMTUyMjU4ODM0Y2RkYzNiN2RkNDNhYjE4N2JkM2Q0ZmQ0M2MwY2JmNmIxODIzZDRlODRjYWEiLCJzaXplIjoyMDY5LCJwbGF0Zm9ybSI6eyJhcmNoaXRlY3R1cmUiOiJhbWQ2NCIsIm9zIjoibGludXgifX0= containerimage.digest:sha256:58193d9f5c0152258834cddc3b7dd43ab187bd3d4fd43c0cbf6b1823d4e84caa image.name:972525491246.dkr.ecr.us-east-1.amazonaws.com/hello-kube:dqa-je-test-dockername-3,972525491246.dkr.ecr.us-east-1.amazonaws.com/hello-kube:506c9805422e38ca3fa38e80bf431865192fc39b]
build completed: state: SUCCESS (duration: 29.922239s) (96 msgs received)
```

**Pull request merged**
